#!/bin/bash

mcs Program.cs BubbleSort.cs SelectionSort.cs InsertionSort.cs MergeSort.cs QuickSort.cs HeapSort.cs RealHeapSort.cs ../tree/BinaryHeap.cs ../linked-list/LinkedList.cs && mono Program.exe
